# Generated by Django 6.0.3 on 2026-06-17 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShortUrl",
            new_name="ShortURLModel",
        ),
        migrations.AlterModelTable(
            name="shorturlmodel",
            table="links_shorturl",
        ),
    ]
