# Generated by Django 6.0.3 on 2026-04-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key for shortified URL",
                        max_length=15,
                        unique=True,
                        verbose_name="URL key",
                    ),
                ),
                ("target_url", models.URLField(verbose_name="Target URL")),
                (
                    "hits",
                    models.PositiveIntegerField(
                        help_text="Total times the URL was requested",
                        verbose_name="Hits",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Short URL",
                "verbose_name_plural": "Short URLs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="links_shorturl_created_at_idx"
                    ),
                    models.Index(fields=["key"], name="links_shorturl_key_idx"),
                    models.Index(
                        condition=models.Q(("created_by_id__isnull", False)),
                        fields=["created_by_id"],
                        name="links_shorturl_created_by_idx",
                    ),
                ],
            },
        ),
    ]
